### ISSUE TITLE
Won't build on boost versions newer than 1.72

### ISSUE THREAD

**Issue by yawor** [kochelmonster/larch-pickle#1]
Hi,

Boost removed boost/detail/endian.hpp in version 1.73. It seems it's been deprecated since 1.71.

**Comment by kochelmonster** [comment]
Are your sure your boost installation is correct? larch-pickle uses <boost/endian/conversion.hpp> and this file exists since 1.71 (if i remember correctly).

**Comment by yawor** [comment]
Ah, the issue is with that there's a really old larch-pickle version (1.1.3) published on pypi.org. I can confirm that the current release from github works. Would it be possible to publish latest version to pypi?

**Comment by kochelmonster** [comment]
I will do this, when I find the time to complete the github workflow.
